all: install demo

demo:
#./do_parafac.sh
	./do_tucker.sh
#	./do_parafacnn.sh
#	./do_tuckernn.sh

demo_parafac:
	./do_parafac.sh

demo_tucker:
	./do_tucker.sh

demo_parafacnn:
	./do_parafacnn.sh

demo_tuckernn:
	./do_tuckernn.sh

install:
	chmod +x *.sh *.jar	

